"""Initial Migration

Revision ID: 93bf8a994eb3
Revises: 3b4580d31725
Create Date: 2020-12-01 02:07:22.158848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bf8a994eb3'
down_revision = '3b4580d31725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.Text(), nullable=False))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###
