"""Initial Migration

Revision ID: 950a380f1799
Revises: 2a0a2b0ef8b6
Create Date: 2020-11-29 21:01:59.979411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950a380f1799'
down_revision = '2a0a2b0ef8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
