"""Initial Migration

Revision ID: afd200d7d8f9
Revises: 3308fba69813
Create Date: 2020-12-01 10:27:15.592772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd200d7d8f9'
down_revision = '3308fba69813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.Text(), nullable=False))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
